# Generated by Django 5.2.1 on 2025-07-04 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0013_alter_companyprofile_email_and_more"),
        ("contacts", "0005_alter_contact_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="company_id",
            field=models.ForeignKey(
                blank=True,
                help_text="Company associated with this contact",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contacts",
                to="companies.companyprofile",
                verbose_name="Company",
            ),
        ),
    ]
