# Generated by Django 5.2.1 on 2025-07-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0006_contact_company_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="language",
            field=models.CharField(
                blank=True,
                choices=[
                    ("en", "English"),
                    ("es", "Spanish"),
                    ("fr", "French"),
                    ("de", "German"),
                    ("it", "Italian"),
                    ("pt", "Portuguese"),
                    ("ukr", "Ukrainian"),
                    ("zh", "Chinese"),
                    ("ja", "Japanese"),
                    ("ko", "Korean"),
                    ("ar", "Arabic"),
                    ("hi", "Hindi"),
                ],
                max_length=255,
                null=True,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="salutation",
            field=models.CharField(
                blank=True,
                choices=[("Mr", "Mr"), ("Ms", "Ms")],
                max_length=255,
                null=True,
                verbose_name="Salutation",
            ),
        ),
    ]
