# Generated by Django 5.2.1 on 2025-07-04 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0013_remove_profile_first_name_remove_profile_last_name"),
        ("contacts", "0007_alter_contact_language_alter_contact_salutation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="contact_created_by",
                to="common.profile",
            ),
        ),
    ]
