# Generated by Django 5.2.1 on 2025-07-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_rename_company_id_contact_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('du', 'Dutch'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('it', 'Italian'), ('pt', 'Portuguese'), ('ukr', 'Ukrainian'), ('zh', 'Chinese'), ('ja', 'Japanese'), ('ko', 'Korean'), ('ar', 'Arabic'), ('hi', 'Hindi')], max_length=255, null=True, verbose_name='Language'),
        ),
    ]
