# Generated by Django 5.2.1 on 2025-07-07 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_remove_profile_first_name_remove_profile_last_name'),
        ('companies', '0013_alter_companyprofile_email_and_more'),
        ('contacts', '0009_rename_company_id_contact_company_and_more'),
        ('leads', '0002_alter_lead_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_company', to='companies.companyprofile'),
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='source',
            new_name='lead_source',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='address_line',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='city',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='close_date',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='contacts',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='country',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='created_from_site',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='enquiry_type',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='opportunity_amount',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='org',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='postcode',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='skype_ID',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='state',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='street',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='teams',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='title',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='website',
        ),
        migrations.AddField(
            model_name='lead',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Amount'),
        ),
        migrations.AddField(
            model_name='lead',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_contact', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Link'),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_created_by', to='common.profile'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_organization', to='common.org'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_updated_by', to='common.profile'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_assigned_to', to='common.profile'),
        ),
    ]
