# Generated by Django 5.2.1 on 2025-07-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_alter_lead_created_by_alter_lead_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='attachment_links',
            field=models.JSONField(blank=True, help_text='Store links to attachments as a JSON array', null=True, verbose_name='Attachment Links'),
        ),
    ]
