# Generated by Django 5.2.1 on 2025-07-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_lead_attachment_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('recycled', 'Recycled')], max_length=255, null=True, verbose_name='Status of Lead'),
        ),
    ]
