# Generated by Django 5.2.1 on 2025-07-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title'),
        ),
    ]
