# Generated by Django 5.2.1 on 2025-07-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_lead_lead_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='converted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Converted to Opportunity'),
        ),
    ]
