# Generated by Django 5.2.4 on 2025-07-28 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0008_lead_converted"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="converted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
