# Generated by Django 5.2.1 on 2025-07-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('qualified', 'Qualified'), ('disqualified', 'Disqualified'), ('recycled', 'Recycled'), ('Rejected', 'Rejected'), ('Duplicate', 'Duplicate')], max_length=64),
        ),
    ]
