# Generated by Django 5.2.1 on 2025-07-16 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0005_alter_case_status"),
        ("common", "0013_remove_profile_first_name_remove_profile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="contract",
            field=models.FileField(
                blank=True,
                help_text="Contract document",
                null=True,
                upload_to="cases/contracts/",
                verbose_name="Contract",
            ),
        ),
        migrations.AddField(
            model_name="case",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for closing (won/lost details)",
                null=True,
                verbose_name="Reason",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="org",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cases",
                to="common.org",
            ),
        ),
        migrations.AlterField(
            model_name="case",
            name="status",
            field=models.BooleanField(
                default=True,
                help_text="True if Won, False if Lost",
                verbose_name="Status",
            ),
        ),
    ]
