# Generated by Django 4.2.23 on 2025-07-29 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0014_alter_opportunity_stage'),
        ('cases', '0006_case_contract_case_reason_alter_case_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='opportunity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lost_feedback_case', to='opportunity.opportunity'),
        ),
    ]
