# Generated by Django 5.2.1 on 2025-06-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_user_first_name_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
