# Generated by Django 5.2.1 on 2025-06-25 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
