# Generated by Django 5.2.1 on 2025-07-16 12:39

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(help_text='The official name of the account/organization', max_length=64, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Primary contact number for the account', max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
