# Generated by Django 5.2.1 on 2025-08-05 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tags_color_alter_account_name_alter_account_phone_and_more'),
        ('companies', '0015_companyprofile_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Company associated with this account', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='companies.companyprofile'),
        ),
    ]
