services:
  crm-app:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: crm-app
    command: bash -c "sleep 10 && cd /app && python3 manage.py collectstatic --noinput && python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - DBNAME=postgres
      - DBUSER=postgres
      - DBPASSWORD=0000
      - DBHOST=crm-db
      - DBPORT=5432
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=False
      - EMAIL_USE_SSL=False
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEFAULT_FROM_EMAIL=crm@example.com
      - ADMIN_EMAIL=admin@example.com
      - DOMAIN_NAME=http://localhost:8000
      - FRONTEND_DOMAIN_NAME=http://localhost:3000
      - SECRET_KEY=your-secret-key
      - ENV_TYPE=dev
      - SWAGGER_ROOT_URL=http://localhost:8000
    depends_on:
      - crm-db
      - mailhog
      - redis
    ports:
      - 8000:8000
    networks:
      - nw
    volumes:
      - ../:/app
      - ../static:/app/static
      - ../staticfiles:/app/staticfiles

  mailhog:
    image: mailhog/mailhog
    container_name: crm-mailhog
    ports:
      - 1025:1025 # SMTP port
      - 8025:8025 # Web UI
    networks:
      - nw
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "1025"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  crm-db:
    image: postgres:latest
    container_name: crm-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    ports:
      - 5432:5432
    volumes:
      - /var/run/postgresql/:/var/run/postgresql
    networks:
      - nw
      
  redis:
    image: redis:latest
    container_name: crm-redis
    ports:
      - 6379:6379
    networks:
      - nw
      
  celery-worker:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: crm-celery
    command: bash -c "cd /app && celery -A crm worker --loglevel=info"
    environment:
      - DBNAME=postgres
      - DBUSER=postgres
      - DBPASSWORD=0000
      - DBHOST=crm-db
      - DBPORT=5432
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
      - EMAIL_USE_TLS=False
      - EMAIL_USE_SSL=False
      - EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DEFAULT_FROM_EMAIL=crm@example.com
      - ADMIN_EMAIL=admin@example.com
      - DOMAIN_NAME=http://localhost:8000
      - FRONTEND_DOMAIN_NAME=http://localhost:3000
      - SECRET_KEY=your-secret-key
      - ENV_TYPE=dev
      - SWAGGER_ROOT_URL=http://localhost:8000
    depends_on:
      - crm-db
      - redis
      - mailhog
    networks:
      - nw
    volumes:
      - ../:/app
      - ../static:/app/static
      - ../staticfiles:/app/staticfiles

networks:
  nw: {}
