# Generated by Django 5.2.1 on 2025-07-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0002_alter_opportunity_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='expected_close_date',
            field=models.DateField(blank=True, help_text='Expected date when this opportunity will be closed', null=True, verbose_name='Expected Close Date'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='expected_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Expected revenue from this opportunity', max_digits=12, null=True, verbose_name='Expected Revenue'),
        ),
    ]
