# Generated by Django 5.2.1 on 2025-07-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0008_lead_converted"),
        ("opportunity", "0003_opportunity_expected_close_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="feedback",
            field=models.TextField(
                blank=True,
                help_text="Feedback or notes related to this opportunity",
                null=True,
                verbose_name="Feedback",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                help_text="Original lead this opportunity was created from",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunities",
                to="leads.lead",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="meeting_date",
            field=models.DateField(
                blank=True,
                help_text="Date of the meeting related to this opportunity",
                null=True,
                verbose_name="Meeting Date",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="proposal_doc",
            field=models.FileField(
                blank=True,
                help_text="Upload proposal document related to this opportunity",
                null=True,
                upload_to="opportunity/proposal_docs/",
                verbose_name="Proposal Document",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
