# Generated by Django 5.2.1 on 2025-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0004_opportunity_feedback_opportunity_lead_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="attachment_links",
            field=models.JSONField(
                blank=True,
                help_text="Store links to attachments as a JSON array",
                null=True,
                verbose_name="Attachment Links",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="proposal_doc",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
