# Generated by Django 5.2.1 on 2025-07-18 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0005_opportunity_attachment_links_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="proposal_doc",
        ),
    ]
