# Generated by Django 5.2.4 on 2025-07-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0008_add_result_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for the result, if lost",
                null=True,
                verbose_name="Reason",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="stage",
            field=models.CharField(
                choices=[
                    ("QUALIFICATION", "QUALIFICATION"),
                    ("IDENTIFY_DECISION_MAKERS", "Identify Decision Makers"),
                    ("PROPOSAL", "Proposal"),
                    ("NEGOTIATION", "Negotiation"),
                    ("CLOSED WON", "CLOSED WON"),
                    ("CLOSED LOST", "CLOSED LOST"),
                ],
                max_length=64,
                verbose_name="Stage",
            ),
        ),
    ]
