# Generated by Django 4.2.23 on 2025-07-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0008_add_result_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('QUALIFICATION', 'QUALIFICATION'), ('IDENTIFY_DECISION_MAKERS', 'Identify Decision Makers'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSED WON', 'CLOSED WON'), ('CLOSED LOST', 'CLOSED LOST')], max_length=64, verbose_name='Stage'),
        ),
    ]
