# Generated by Django 5.2.4 on 2025-07-21 06:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0009_opportunity_reason_alter_opportunity_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="reason",
        ),
    ]
