# Generated by Django 5.2.4 on 2025-07-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("opportunity", "0010_remove_opportunity_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="contract_attachment",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Store links to contract attachments as a JSON array",
                null=True,
                verbose_name="Contract Attachment",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="Reason for the result of the opportunity, if lost",
                null=True,
                verbose_name="Reason",
            ),
        ),
    ]
