# Generated by Django 5.2.1 on 2025-07-23 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0009_alter_opportunity_stage'),
        ('opportunity', '0012_alter_opportunity_stage'),
    ]

    operations = [
    ]
