# Generated by Django 5.2.1 on 2025-07-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunity', '0013_merge_20250723_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('QUALIFICATION', 'QUALIFICATION'), ('IDENTIFY_DECISION_MAKERS', 'Identify Decision Makers'), ('PROPOSAL', 'Proposal'), ('NEGOTIATION', 'Negotiation'), ('CLOSE', 'Close'), ('CLOSED WON', 'CLOSED WON'), ('CLOSED LOST', 'CLOSED LOST')], max_length=64, verbose_name='Stage'),
        ),
    ]
