# Generated by Django 5.2.1 on 2025-07-02 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_companyprofile_delete_company"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="companyprofile",
            table="companies",
        ),
    ]
