# Generated by Django 5.2.1 on 2025-07-03 09:06

import django.core.validators
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0013_remove_profile_first_name_remove_profile_last_name"),
        ("companies", "0004_alter_companyprofile_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="billing_address_number",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Address number can only contain letters, numbers, hyphens, slashes, and spaces",
                        regex="^[a-zA-Z0-9\\-\\/\\s]+$",
                    )
                ],
                verbose_name="Billing Address Number",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="billing_city",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="City name can only contain letters, spaces, hyphens, apostrophes, and dots",
                        regex="^[a-zA-Z\\s\\-\\'\\.]+$",
                    )
                ],
                verbose_name="Billing City",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="billing_postcode",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Postcode format is invalid",
                        regex="^[A-Za-z0-9\\s\\-]+$",
                    )
                ],
                verbose_name="Billing Postcode",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="billing_street",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Street address contains invalid characters",
                        regex="^[a-zA-Z0-9\\s\\-\\.\\,\\'\\\"]+$",
                    )
                ],
                verbose_name="Billing Street",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="email",
            field=models.EmailField(
                blank=True,
                db_index=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.EmailValidator(
                        code="invalid_email", message="Enter a valid email address."
                    )
                ],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="industry",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADVERTISING", "ADVERTISING"),
                    ("AGRICULTURE", "AGRICULTURE"),
                    ("APPAREL & ACCESSORIES", "APPAREL & ACCESSORIES"),
                    ("AUTOMOTIVE", "AUTOMOTIVE"),
                    ("BANKING", "BANKING"),
                    ("BIOTECHNOLOGY", "BIOTECHNOLOGY"),
                    (
                        "BUILDING MATERIALS & EQUIPMENT",
                        "BUILDING MATERIALS & EQUIPMENT",
                    ),
                    ("CHEMICAL", "CHEMICAL"),
                    ("COMPUTER", "COMPUTER"),
                    ("EDUCATION", "EDUCATION"),
                    ("ELECTRONICS", "ELECTRONICS"),
                    ("ENERGY", "ENERGY"),
                    ("ENTERTAINMENT & LEISURE", "ENTERTAINMENT & LEISURE"),
                    ("FINANCE", "FINANCE"),
                    ("FOOD & BEVERAGE", "FOOD & BEVERAGE"),
                    ("GROCERY", "GROCERY"),
                    ("HEALTHCARE", "HEALTHCARE"),
                    ("INSURANCE", "INSURANCE"),
                    ("LEGAL", "LEGAL"),
                    ("MANUFACTURING", "MANUFACTURING"),
                    ("PUBLISHING", "PUBLISHING"),
                    ("REAL ESTATE", "REAL ESTATE"),
                    ("SERVICE", "SERVICE"),
                    ("SOFTWARE", "SOFTWARE"),
                    ("SPORTS", "SPORTS"),
                    ("TECHNOLOGY", "TECHNOLOGY"),
                    ("TELECOMMUNICATIONS", "TELECOMMUNICATIONS"),
                    ("TELEVISION", "TELEVISION"),
                    ("TRANSPORTATION", "TRANSPORTATION"),
                    ("VENTURE CAPITAL", "VENTURE CAPITAL"),
                ],
                db_index=True,
                max_length=255,
                null=True,
                verbose_name="Industry Type",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=255,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Company name can only contain letters, numbers, spaces, hyphens, dots, ampersands, and parentheses",
                        regex="^[a-zA-Z0-9\\s\\-\\.\\&\\(\\)]+$",
                    )
                ],
                verbose_name="Company Name",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="International format: +31234567890",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="website",
            field=models.URLField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        message="Website must be a valid URL starting with http:// or https://",
                        schemes=["http", "https"],
                    )
                ],
                verbose_name="Website",
            ),
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(
                fields=["name", "org"], name="companies_name_cabb6b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(
                fields=["email", "org"], name="companies_email_03bc8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(
                fields=["industry"], name="companies_industr_7891ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(
                fields=["created_at"], name="companies_created_c84a3d_idx"
            ),
        ),
    ]
