# Generated by Django 5.2.1 on 2025-07-03 11:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0013_remove_profile_first_name_remove_profile_last_name"),
        ("companies", "0005_alter_companyprofile_billing_address_number_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companyprofile",
            unique_together={("email", "org"), ("name", "org"), ("website", "org")},
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="industry",
            field=models.CharField(
                choices=[
                    ("ADVERTISING", "ADVERTISING"),
                    ("AGRICULTURE", "AGRICULTURE"),
                    ("APPAREL & ACCESSORIES", "APPAREL & ACCESSORIES"),
                    ("AUTOMOTIVE", "AUTOMOTIVE"),
                    ("BANKING", "BANKING"),
                    ("BIOTECHNOLOGY", "BIOTECHNOLOGY"),
                    (
                        "BUILDING MATERIALS & EQUIPMENT",
                        "BUILDING MATERIALS & EQUIPMENT",
                    ),
                    ("CHEMICAL", "CHEMICAL"),
                    ("COMPUTER", "COMPUTER"),
                    ("EDUCATION", "EDUCATION"),
                    ("ELECTRONICS", "ELECTRONICS"),
                    ("ENERGY", "ENERGY"),
                    ("ENTERTAINMENT & LEISURE", "ENTERTAINMENT & LEISURE"),
                    ("FINANCE", "FINANCE"),
                    ("FOOD & BEVERAGE", "FOOD & BEVERAGE"),
                    ("GROCERY", "GROCERY"),
                    ("HEALTHCARE", "HEALTHCARE"),
                    ("INSURANCE", "INSURANCE"),
                    ("LEGAL", "LEGAL"),
                    ("MANUFACTURING", "MANUFACTURING"),
                    ("PUBLISHING", "PUBLISHING"),
                    ("REAL ESTATE", "REAL ESTATE"),
                    ("SERVICE", "SERVICE"),
                    ("SOFTWARE", "SOFTWARE"),
                    ("SPORTS", "SPORTS"),
                    ("TECHNOLOGY", "TECHNOLOGY"),
                    ("TELECOMMUNICATIONS", "TELECOMMUNICATIONS"),
                    ("TELEVISION", "TELEVISION"),
                    ("TRANSPORTATION", "TRANSPORTATION"),
                    ("VENTURE CAPITAL", "VENTURE CAPITAL"),
                ],
                db_index=True,
                default=2,
                help_text="Select the industry type of the company",
                max_length=255,
                verbose_name="Industry Type",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="companyprofile",
            index=models.Index(
                fields=["website", "org"], name="companies_website_b62abd_idx"
            ),
        ),
    ]
