# Generated by Django 5.2.1 on 2025-07-03 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_alter_companyprofile_billing_address_number_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            # Очищаем дублирующиеся website
            sql="""
            UPDATE companies
            SET website = NULL
            WHERE id IN (
                SELECT id FROM (
                    SELECT id,
                           ROW_NUMBER() OVER (PARTITION BY website, org_id ORDER BY created_at) as rn
                    FROM companies
                    WHERE website IS NOT NULL
                ) ranked
                WHERE rn > 1
            );
            """,
            reverse_sql="-- No reverse operation needed",
        ),
        migrations.RunSQL(
            # Исправляем неправильные значения industry
            sql="UPDATE companies SET industry = 'AGRICULTURE' WHERE industry = '2' OR industry IS NULL;",

            # Откат миграции (если понадобится)
            reverse_sql="UPDATE companies SET industry = NULL WHERE industry = 'AGRICULTURE';",
        ),
    ]
