# Generated by Django 5.2.1 on 2025-07-03 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0013_remove_profile_first_name_remove_profile_last_name"),
        ("companies", "0007_auto_20250703_1716"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="companyprofile",
            unique_together={("email", "org"), ("name", "org")},
        ),
    ]
