# Generated by Django 5.2.1 on 2025-07-03 11:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0006_alter_companyprofile_unique_together_and_more"),
        ("companies", "0008_alter_companyprofile_unique_together"),
    ]

    operations = []
