# Generated by Django 5.2.1 on 2025-07-03 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0009_merge_20250703_1721"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="website",
            field=models.CharField(
                blank=True,
                help_text="Website URL of the company",
                max_length=255,
                null=True,
                verbose_name="Website",
            ),
        ),
    ]
