# Generated by Django 5.2.1 on 2025-07-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0011_alter_companyprofile_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="website",
            field=models.CharField(
                blank=True,
                help_text="Website URL of the company",
                max_length=255,
                null=True,
                verbose_name="Website",
            ),
        ),
    ]
