# Generated by Django 5.2.1 on 2025-07-04 09:23

import django.core.validators
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0012_alter_companyprofile_website"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=255,
                validators=[
                    django.core.validators.EmailValidator(
                        code="invalid_email", message="Enter a valid email address."
                    )
                ],
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                help_text="International format: +31234567890",
                max_length=128,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="companyprofile",
            name="website",
            field=models.CharField(
                help_text="Website URL of the company",
                max_length=255,
                validators=[
                    django.core.validators.URLValidator(
                        message="Website must be a valid URL starting with http:// or https://",
                        schemes=["http", "https"],
                    )
                ],
                verbose_name="Website",
            ),
        ),
    ]
