# Generated by Django 5.2.1 on 2025-07-07 18:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0013_alter_companyprofile_email_and_more"),
        ("companies", "0013_companyprofile_billing_state_and_more"),
    ]

    operations = []
