# Generated by Django 4.2.23 on 2025-07-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0014_merge_20250707_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='logo_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for the company logo', max_length=500, null=True, verbose_name='Company Logo URL'),
        ),
    ]
