# Generated by Django 5.2.1 on 2025-08-05 04:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_company'),
        ('companies', '0015_companyprofile_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='account',
            field=models.ForeignKey(blank=True, help_text='Account created for this company when opportunity is closed won', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_companies', to='accounts.account'),
        ),
    ]
